
import { Profile, Medicine, Schedule, DoseStatus } from '../types';

declare const jspdf: any;

interface ReportData {
  profile: Profile;
  medicines: Medicine[];
  schedules: Schedule[];
  startDate: Date;
  endDate: Date;
}

export const generatePDFReport = async (data: ReportData): Promise<void> => {
  const { profile, medicines, schedules, startDate, endDate } = data;
  const { jsPDF } = jspdf;
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235); // primary-600
  doc.text('Medicine History Report', 105, 20, { align: 'center' });

  // Profile Information
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(`Profile: ${profile.name}`, 14, 35);
  doc.text(`Report Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`, 14, 42);
  
  if (profile.picture) {
    try {
        doc.addImage(profile.picture, 'JPEG', 160, 28, 35, 35);
    } catch(e) {
        console.error("Failed to add profile picture to PDF", e);
    }
  }

  // Compliance Score
  const totalDoses = schedules.length;
  const takenDoses = schedules.filter(s => s.status === DoseStatus.TAKEN).length;
  const complianceRate = totalDoses > 0 ? ((takenDoses / totalDoses) * 100).toFixed(1) : 'N/A';
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Overall Compliance: ${complianceRate}%`, 105, 60, { align: 'center' });
  doc.setLineWidth(0.5);
  doc.line(14, 65, 196, 65);

  let yPos = 75;

  const medicineMap = new Map<string, Medicine>(medicines.map(m => [m.id, m]));

  for (const medicine of medicines) {
    const medicineSchedules = schedules.filter(s => s.medicineId === medicine.id);
    if (medicineSchedules.length === 0) continue;

    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(13, 148, 136); // secondary-600
    doc.text(`${medicine.name} (${medicine.dose})`, 14, yPos);
    yPos += 7;

    if (medicine.doctorName) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139); // slate-500
        doc.text(`Prescribed by: ${medicine.doctorName}`, 14, yPos);
        yPos += 5;
    }

    if (medicine.prescriptionImage) {
        if (yPos > 180) { // Check if there's enough space for image and table
            doc.addPage();
            yPos = 20;
        }
        try {
            doc.addImage(medicine.prescriptionImage, 'JPEG', 14, yPos, 60, 40);
        } catch(e) {
            console.error("Error adding prescription image", e);
        }
        yPos += 45;
    }
    
    const tableBody = medicineSchedules
        .sort((a,b) => new Date(a.scheduledTime).getTime() - new Date(b.scheduledTime).getTime())
        .map(s => {
            const scheduled = new Date(s.scheduledTime);
            const actual = s.actualTakenTime ? new Date(s.actualTakenTime) : null;
            return [
                scheduled.toLocaleString(),
                actual ? actual.toLocaleString() : '-',
                s.status.charAt(0).toUpperCase() + s.status.slice(1)
            ];
        });

    doc.autoTable({
      startY: yPos,
      head: [['Scheduled Time', 'Actual Time Taken', 'Status']],
      body: tableBody,
      theme: 'grid',
      headStyles: { fillColor: [20, 184, 166] }, // secondary-500
      didDrawPage: (data: any) => {
        yPos = data.cursor.y;
      }
    });

    yPos = doc.previousAutoTable.finalY + 10;
  }


  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Page ${i} of ${pageCount}`, 105, 287, { align: 'center' });
    doc.text(`Generated by Medicine Reminder on ${new Date().toLocaleString()}`, 105, 292, { align: 'center' });
  }

  doc.save(`${profile.name}_Medication_Report.pdf`);
};
